# Generated by Django 5.0.2 on 2024-02-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_client_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='assigned_user',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
