# Generated by Django 5.0.2 on 2024-02-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_client_assigned_user_alter_client_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='uniqueid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_by',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
