# Generated by Django 5.0.2 on 2024-02-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=200, null=True)),
                ('uname', models.CharField(max_length=200, null=True)),
                ('pwd', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
