# Generated by Django 5.0.2 on 2024-02-20 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_project_delete_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cname',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.client'),
        ),
    ]
