# Generated by Django 5.0.2 on 2024-02-20 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_project_cname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
